config/routes.rb
Rails.application.routes.draw do
  root 'static_bblws#home'

  get '/about', to: 'static_bblws#about'

  resources :bblws
end

# This will automatically include all of our basic CRUD routes 
# for pages (PRO TIP: rake routes will show all routes).

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bblw.rb
class Bblw < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bblws_controller.rb
class BblwsController < ApplicationController
  def index
    @bblws = Bblw.all
  end
  # Page.all => Returns all pages in the database

  def show
    @bblw = Bblw.find(params[:id])
  end
  # Page.find(#) => Finds a page by the id passed in

  def new
    @bblw = Bblw.new
  end
# Page.new => Creates a new page in memory that is not yet saved to the db


def create
  @bblw = Bblw.new(bblws_params)
  if @bblw.save
    redirect_to bblws_path
  else
    render :new
  end 
end

private
def bblws_params
  params.require(:bblw).permit(:title, :author, :category, :body)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bblws_helper.rb
module BblwsHelper
end

app/views/bblws/index.html.erb
<h1>BBLW BLOG: SEND US YOUR SUBMISSIONS!</h1>
<p><%= link_to 'New Submission', new_bblw_path %></p>
<% @bblws.each do |bblws| %>
<h2><%= bblws.title %></h2>
<%= link_to  "Submit you entry here", bblws_path(bblws) %>
<% end %>

app/views/bblws/new.html.erb
<h1>New Page</h1>
<%= form_for @bblw do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>

  <%= f.label :author %>
  <%= f.text_field :author %>

  <%= f.label :category %>
  <%= f.text_field :category %>

  <%= f.label :body %>
  <%= f.text_area :body %>

  <%= f.submit %>
<% end %>

app/views/bblws/show.html.erb
<h1><%= @bblw.title %></h1>
<h4><%= @bblw.author %></h1>
<p><%= @bblw.category %></p>
<p><%= @bblw.body %></p>
<%= link_to 'Back', bblws_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsBblwBlog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>